# These are supported funding model platforms

github: Ganesh2506  # Replace with your GitHub username
patreon: # Add your Patreon username if you create one
open_collective: # Add if you create one
ko_fi: # Add your Ko-fi username if you create one
tidelift: # Add if applicable
community_bridge: # Add if applicable
liberapay: # Add if you create one
issuehunt: # Add if applicable
custom: ['https://www.buymeacoffee.com/ganesh2506']  # Replace with your Buy Me a Coffee link
